vision_artag_node:
  ros__parameters:
    input_source: "/dev/video4"
    input_width: 640
    input_height: 480
    show_window: true
    window_name: "vision_artag"
    enable_stream: false
    stream_host: "10.7.101.148"
    stream_port: 5000
    stream_width: 640
    stream_height: 480
    stream_fps: 30
    stream_bitrate_kbps: 500
    tag_id: -1
    tag_size_m: 0.2
    pose_frame_id: "camera"
    offset_x_m: 0.0
    offset_y_m: 0.0
    offset_z_m: 0.0
    camera_matrix:
      - 504.99132615
      - 0.0
      - 318.4012728
      - 0.0
      - 506.13168687
      - 243.99035432
      - 0.0
      - 0.0
      - 1.0
    distortion_coeffs:
      - 0.07771398
      - -0.18711237
      - -0.00182709
      - 0.00026326
      - -0.06212367
    filter.min_area_ratio: 0.0006
    filter.max_area_ratio: 0.8
    filter.max_squareness_ratio: 1.4
    filter.min_border_px: 6
    filter.stable_frames: 1
    filter.max_center_jump_px: 100.0
    aruco.adaptive_thresh_win_size_min: 3
    aruco.adaptive_thresh_win_size_max: 53
    aruco.adaptive_thresh_win_size_step: 10
    aruco.adaptive_thresh_constant: 7.0
    aruco.min_marker_perimeter_rate: 0.02
    aruco.max_marker_perimeter_rate: 4.0
    aruco.polygonal_approx_accuracy_rate: 0.05
    aruco.min_corner_distance_rate: 0.05
    aruco.min_marker_distance_rate: 0.05
    aruco.min_distance_to_border: 3
    aruco.detect_inverted_marker: true
    aruco.error_correction_rate: 0.6
    aruco.corner_refine_method: 2
    aruco.corner_refine_win_size: 5
    aruco.corner_refine_max_iterations: 30
    aruco.corner_refine_min_accuracy: 0.1
