
/**/mavros_node:
  ros__parameters:
    fcu_url: "/dev/serial/by-id/usb-ArduPilot_Pixhawk6X_2D004C001151323530363730-if00:115200"
    gcs_url: "udp://@100.95.74.67:14550"
    tgt_system: 1
    tgt_component: 1
    fcu_protocol: "v2.0"
    log_output: "screen"

/**/distance_sensor:
  ros__parameters:
    config: 
      rangefinder_pub:
        id: 0
        frame_id: "lidar"
        orientation: PITCH_270
        field_of_view: 0.0
        send_tf: false
        sensor_position: {x: 0.0, y: 0.0, z: -0.1}
